version: '3'

services:
  reverse-proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  app:
    build:
      context: .
      dockerfile: Dockerfile